[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 119
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true

[tool.flake8]
max-line-length = 119
extend-ignore = ["E203", "W503"]

[tool.pytest.ini_options]
# Пути для импорта модулей
python_paths = ["src"]
# Папки с тестами
testpaths = ["tests"]
# Игнорировать папки
addopts = "--ignore=tests/legacy --ignore=docs"
# Включить цветную подсветку
color = "yes"
# Verbose output
verbose = 1

[project]
name = "my-project"
version = "0.1.0"
